### ISSUE TITLE
git geo setup fails after successful installation

### ISSUE THREAD

**Issue by voidus** [peritus/geocommit#4]
After installing successfully via `easy_install geocommit` I get the following error when I try `git geo setup` in a project's directory

```
void@lnvo> git geo setup
Traceback (most recent call last):
  File "/usr/local/bin/git-geo", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.6/dist-packages/pkg_resources.py", line 2655, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.6/dist-packages/pkg_resources.py", line 648, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.6/dist-packages/pkg_resources.py", line 546, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: geocommit==0.9.2
```

I'm running mint linux isadora which is based on ubuntu 10.04.

**Comment by peritus** [comment]
I'll look into that ASAP. Can you try using `pip install --upgrade geocommit` (`easy_install pip` first, if you don't have pip yet) ?
