### ISSUE TITLE
Errors when using geocommit

### ISSUE THREAD

**Issue by lamemate** [peritus/geocommit#5]
When trying to use geocommit I get the following error:

```
Traceback (most recent call last):
File "/usr/local/bin/git-geo", line 8, in <module>
load_entry_point('geocommit==0.9.2', 'console_scripts', 'git-geo')()

File "/Library/Python/2.6/site-packages/geocommit-0.9.2-py2.6-macosx-10.6-universal.egg/geocommit/__init__.py", line 311, in git_geo
f(sys.argv[2:])

File "/Library/Python/2.6/site-packages/geocommit-0.9.2-py2.6-macosx-10.6-universal.egg/geocommit/__init__.py", line 165, in cmd_note
note = self.get_note()

File "/Library/Python/2.6/site-packages/geocommit-0.9.2-py2.6-macosx-10.6-universal.egg/geocommit/__init__.py", line 49, in get_note
location = provider.get_location()

File "/Library/Python/2.6/site-packages/geocommit-0.9.2-py2.6-macosx-10.6-universal.egg/geocommit/provider/corelocation/__init__.py", line 71, in get_location
return self.parse_funky_description_dump(parseme)

File "/Library/Python/2.6/site-packages/geocommit-0.9.2-py2.6-macosx-10.6-universal.egg/geocommit/provider/corelocation/__init__.py", line 62, in
parse_funky_description_dump

loc = Location(lat, lng, src='cl')
UnboundLocalError: local variable 'lat' referenced before assignment
```

I'm running Mac OS X 10.6.6 and installed it by running `easy_install geocommit`. After installing pip I used `pip install --upgrade geocommit` to install it again, to no avail.

**Comment by peritus** [comment]
The code segment in the stacktrace is gone in geocommit 0.9.3beta1, you can upgrade with `pip install --upgrade geocommit`, the error should be gone.
